/// Flutter icons Pokebowl
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pokebowl
///      fonts:
///       - asset: fonts/Pokebowl.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Pokebowl {
  Pokebowl._();

  static const _kFontFam = 'Pokebowl';

  static const IconData hamburger = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow_right = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData arrow_left = IconData(0xe802, fontFamily: _kFontFam);
}
